# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Free Agent Realty - The Best Deal In Real Estate
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  properties:
    title: Properties
    output: true
  reviews:
    title: Reviews
    output: true
  uploads:
    title: Uploads
    output: true
email: grant@freeagentrealty.com
description: Free Agent Realty is a local real estate company serving the Madison Wisconsin area and its surrounding communities. At Free Agent Realty we provide all around dedicated customer service, without the commission, when you sell your home.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.freeagentrealty.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
